// src/components/Header.tsx
import logo from "../imgs/aiko.png";
import EquipmentList from "./EquipmentList";

function Header() {
	return (
		<header className="flex flex-col min-h-screen min-w-[200px] max-w-[280px] overflow-auto border-r border-gray-500">
			<a href="#">
				<img className="flex-1 px-10 bg-gray-400 bg-center bg-no-repeat bg-cover bg-blend-multiply py-14 bg-backgroundLogo" src={logo} alt="Aiko" />
			</a>

			<EquipmentList />
		</header>
	);
}

export default Header;

// src/components/Header.vue
<template>
  <section class="header-master">
    <a href="https://aiko.digital"><img src="../assets/imgs/aiko.png"></a>
  </section>
</template>

<script>
export default {

};
</script>

<style>
  .header-master {
    margin: 0!important;
    padding: 0;
    background-image: url('../assets/imgs/banner-florestal-ok.jpg');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    min-height: 300px;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .header-master a img{
    max-height: 70px;
  }
  h1 {
    margin: 0;
  }
</style>
